// Generated by `yarn configure`: the UI of each selected module (packages/nextjs/modules/<id>/index.ts).
import type { ComponentType } from "react";
import coreView from "./core";
import dexView from "./dex";
import flashloanView from "./flashloan";
import paymentsView from "./payments";
import rwaView from "./rwa";

/** Views render next to the setup hint with `ready` = all required env vars set. */
export const moduleViews: Record<string, ComponentType<{ ready: boolean }>> = {
  core: coreView,
  rwa: rwaView,
  dex: dexView,
  payments: paymentsView,
  flashloan: flashloanView,
};
