import type { EnvVar, IntegrationRecipe, ModuleManifest } from "./define";
import type { Resolution } from "./resolve";

/** Marks where the generated, manifest-driven part of .env.example starts. */
export const ENV_MARKER = "# ---- Module settings (generated by `yarn configure` from the module manifests) ----";

/** Source of modules.config.ts for a resolution. Manifest files live at ./modules/<id> and ./integrations/<id>. */
export function renderModulesConfig(resolution: Resolution): string {
  const ident = (id: string) => id.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ?? "").toUpperCase());
  // Sorted by path, the order Prettier's import sorting produces, so the output is stable.
  const imports = [
    ...resolution.modules.map(m => [`./modules/${m.id}`, ident(m.id)]),
    ...resolution.integrations.map(r => [`./integrations/${r.id}`, ident(r.id)]),
  ]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, name]) => `import { ${name} } from "${from}";`);
  return [
    "// Selected modules and integration recipes. `yarn configure` rewrites this file.",
    'import type { IntegrationRecipe, ModuleManifest } from "./define";',
    ...imports,
    "",
    `export const modules: ModuleManifest[] = [${resolution.modules.map(m => ident(m.id)).join(", ")}];`,
    `export const integrations: IntegrationRecipe[] = [${resolution.integrations.map(r => ident(r.id)).join(", ")}];`,
    "",
  ].join("\n");
}

/** Source of the Next.js view registry: one default-exported view per module or recipe folder that has one. */
export function renderViewRegistry(moduleIdsWithViews: string[]): string {
  const ident = (id: string) => `${id.replace(/[^a-zA-Z0-9]/g, "_")}View`;
  return [
    "// Generated by `yarn configure`: the UI of each selected module and recipe (packages/nextjs/modules/<id>/index.ts).",
    'import type { ComponentType } from "react";',
    ...moduleIdsWithViews.map(id => `import ${ident(id)} from "./${id}";`).sort(),
    "",
    "/** Views render next to the setup hint with `ready` = all required env vars set. */",
    "export const moduleViews: Record<string, ComponentType<{ ready: boolean }>> = {",
    ...moduleIdsWithViews.map(id => `  ${/^[a-z_$][\w$]*$/i.test(id) ? id : JSON.stringify(id)}: ${ident(id)},`),
    "};",
    "",
  ].join("\n");
}

/** Replaces everything after ENV_MARKER with one commented block per env var. */
export function renderEnvExample(current: string, vars: EnvVar[]): string {
  const head = current.includes(ENV_MARKER)
    ? current.slice(0, current.indexOf(ENV_MARKER))
    : `${current.trimEnd()}\n\n`;
  const body = vars.map(v => `# ${v.description}${v.required ? "" : " (optional)"}\n${v.key}=`).join("\n");
  return `${head}${ENV_MARKER}\n${body}\n`;
}

/**
 * Paths, package scripts and npm dependencies owned by modules and recipes that the resolution
 * does not keep. Anything a kept module or recipe also owns is never pruned.
 */
export function prunePlan(catalog: ModuleManifest[], recipes: IntegrationRecipe[], resolution: Resolution) {
  const keptItems = [...resolution.modules, ...resolution.integrations];
  const kept = new Set<object>(keptItems);
  const dropped = [...catalog, ...recipes].filter(item => !kept.has(item));
  const keep = (pick: (i: ModuleManifest | IntegrationRecipe) => string[]) => new Set(keptItems.flatMap(pick));
  const keptPaths = keep(i => i.paths);
  const keptScripts = keep(i => i.scripts);
  const keptDeps = keep(i => i.dependencies);
  const unique = (values: string[], exclude: Set<string>) => [...new Set(values)].filter(v => !exclude.has(v));
  return {
    paths: unique(
      dropped.flatMap(d => d.paths),
      keptPaths,
    ),
    scripts: unique(
      dropped.flatMap(d => d.scripts),
      keptScripts,
    ),
    dependencies: unique(
      dropped.flatMap(d => d.dependencies),
      keptDeps,
    ),
  };
}

/** True when `path` is a non-empty relative path that stays inside the repo (no "", ".", "..", absolute). */
export function isSafeRepoPath(path: string): boolean {
  const parts = path.split(/[\\/]+/);
  return path.trim() !== "" && !/^([a-zA-Z]:)?[\\/]/.test(path) && parts.every(p => p !== "..") && path !== ".";
}
