import type { EnvVar, IntegrationRecipe, ModuleManifest } from "./define";
import type { Resolution } from "./resolve";

/** Marks where the generated, manifest-driven part of .env.example starts. */
export const ENV_MARKER = "# ---- Module settings (generated by `yarn configure` from the module manifests) ----";

/** Source of modules.config.ts for a resolution. Manifest files live at ./modules/<id> and ./integrations/<id>. */
export function renderModulesConfig(resolution: Resolution): string {
  const ident = (id: string) => id.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ?? "").toUpperCase());
  const imports = [
    ...resolution.modules.map(m => `import { ${ident(m.id)} } from "./modules/${m.id}";`),
    ...resolution.integrations.map(r => `import { ${ident(r.id)} } from "./integrations/${r.id}";`),
  ].sort();
  return [
    "// Selected modules and integration recipes. `yarn configure` rewrites this file.",
    'import type { IntegrationRecipe, ModuleManifest } from "./define";',
    ...imports,
    "",
    `export const modules: ModuleManifest[] = [${resolution.modules.map(m => ident(m.id)).join(", ")}];`,
    `export const integrations: IntegrationRecipe[] = [${resolution.integrations.map(r => ident(r.id)).join(", ")}];`,
    "",
  ].join("\n");
}

/** Source of the Next.js view registry: one default-exported view per module folder that has one. */
export function renderViewRegistry(moduleIdsWithViews: string[]): string {
  const ident = (id: string) => `${id.replace(/[^a-zA-Z0-9]/g, "_")}View`;
  return [
    "// Generated by `yarn configure`: the UI of each selected module (packages/nextjs/modules/<id>/index.ts).",
    'import type { ComponentType } from "react";',
    ...moduleIdsWithViews.map(id => `import ${ident(id)} from "./${id}";`).sort(),
    "",
    "/** Views render next to the setup hint with `ready` = all required env vars set. */",
    "export const moduleViews: Record<string, ComponentType<{ ready: boolean }>> = {",
    ...moduleIdsWithViews.map(id => `  ${/^[a-z_$][\w$]*$/i.test(id) ? id : JSON.stringify(id)}: ${ident(id)},`),
    "};",
    "",
  ].join("\n");
}

/** Replaces everything after ENV_MARKER with one commented block per env var. */
export function renderEnvExample(current: string, vars: EnvVar[]): string {
  const head = current.includes(ENV_MARKER)
    ? current.slice(0, current.indexOf(ENV_MARKER))
    : `${current.trimEnd()}\n\n`;
  const body = vars.map(v => `# ${v.description}${v.required ? "" : " (optional)"}\n${v.key}=`).join("\n");
  return `${head}${ENV_MARKER}\n${body}\n`;
}

/** Paths and package scripts owned by modules and recipes that the resolution does not keep. */
export function prunePlan(catalog: ModuleManifest[], recipes: IntegrationRecipe[], resolution: Resolution) {
  const kept = new Set<object>([...resolution.modules, ...resolution.integrations]);
  const dropped = [...catalog, ...recipes].filter(item => !kept.has(item));
  return { paths: dropped.flatMap(d => d.paths), scripts: dropped.flatMap(d => d.scripts) };
}
